var KEY="wyceny-v1";
var db=JSON.parse(localStorage.getItem(KEY)||'{"quotes":[],"services":[{"name":"Montaż kamery","price":150},{"name":"Konfiguracja rejestratora","price":200},{"name":"Montaż alarmu","price":300},{"name":"Montaż zamka/wkładki","price":100},{"name":"Dojazd","price":50},{"name":"Konfiguracja sieci","price":150}]}');
var view="home",draft=null;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return Number(n||0).toFixed(2).replace(".",",")+" zł"}
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]})}
function nav(){return '<nav class="nav"><button onclick="go(\'home\')">🏠 Start</button><button onclick="newQuote()">➕ Wycena</button><button onclick="go(\'quotes\')">📋 Wyceny</button><button onclick="go(\'clients\')">👥 Klienci</button></nav>'}
function go(v){view=v;render()}
function newQuote(){draft={client:"",date:new Date().toISOString().slice(0,10),items:[],note:""};view="new";render()}
function render(){var body=view==="home"?home():view==="new"?editor():view==="quotes"?quotes():view==="services"?services():clients();document.getElementById("app").innerHTML='<header class="top"><h1>Wyceny Montażu</h1><p>Szybkie wyceny na telefonie</p></header><main class="wrap">'+body+'</main>'+nav()}
function home(){var sum=db.quotes.reduce(function(a,q){return a+q.total},0);return '<div class="grid"><div class="card"><div class="muted">Liczba wycen</div><div class="stat">'+db.quotes.length+'</div></div><div class="card"><div class="muted">Wartość</div><div class="stat">'+money(sum)+'</div></div></div><button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button><div class="card" style="margin-top:12px"><b>Cennik</b><p class="muted">'+db.services.length+' usług</p><button class="btn secondary" onclick="go(\'services\')">Edytuj cennik</button></div>'}
function editor(){var rows=draft.items.map(function(x,i){return '<div class="item"><input class="input" placeholder="Usługa / materiał" value="'+esc(x.name)+'" oninput="draft.items['+i+'].name=this.value"><input class="input qty" type="number" min="1" value="'+x.qty+'" oninput="draft.items['+i+'].qty=+this.value;refreshTotal()"><input class="input price" type="number" min="0" value="'+x.price+'" oninput="draft.items['+i+'].price=+this.value;refreshTotal()"><button class="btn danger" onclick="draft.items.splice('+i+',1);render()">×</button></div>'}).join("");var total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);return '<button class="btn secondary" onclick="go(\'home\')">← Wróć</button><div class="form"><b>Klient</b><input class="input" placeholder="Imię i nazwisko / firma" value="'+esc(draft.client)+'" oninput="draft.client=this.value"><b>Data</b><input class="input" type="date" value="'+draft.date+'" oninput="draft.date=this.value"><b>Pozycje</b>'+rows+'<button class="btn secondary" onclick="addItem()">＋ Dodaj pozycję</button><div id="total" class="total">Razem: '+money(total)+'</div><textarea class="input" rows="3" placeholder="Uwagi" oninput="draft.note=this.value">'+esc(draft.note)+'</textarea><button class="btn primary" onclick="saveQuote()">💾 Zapisz wycenę</button></div>'}
function addItem(){draft.items.push({name:"",qty:1,price:0});render()}
function refreshTotal(){var t=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);var e=document.getElementById("total");if(e)e.textContent="Razem: "+money(t)}
function saveQuote(){if(!draft.client.trim()){alert("Wpisz klienta.");return}draft.total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);draft.id=Date.now();db.quotes.unshift(draft);save();view="quotes";render()}
function quotes(){if(!db.quotes.length)return '<div class="empty">Brak wycen.<br><br><button class="btn primary" onclick="newQuote()">Utwórz pierwszą</button></div>';return '<button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button>'+db.quotes.map(function(q){return '<div class="card"><b>'+esc(q.client)+'</b><div class="muted">'+q.date+' · '+q.items.length+' pozycji</div><div class="total">'+money(q.total)+'</div><button class="btn secondary" onclick="shareQuote('+q.id+')">📤 Udostępnij</button> <button class="btn danger" onclick="delQuote('+q.id+')">Usuń</button></div>'}).join("")}
function delQuote(id){db.quotes=db.quotes.filter(function(q){return q.id!==id});save();render()}
function shareQuote(id){var q=db.quotes.find(function(x){return x.id===id});var text="WYCENA\nKlient: "+q.client+"\nData: "+q.date+"\n\n"+q.items.map(function(x){return x.name+" × "+x.qty+" = "+money(x.qty*x.price)}).join("\n")+"\n\nRAZEM: "+money(q.total)+(q.note?"\nUwagi: "+q.note:"");if(navigator.share)navigator.share({title:"Wycena",text:text});else navigator.clipboard.writeText(text).then(function(){alert("Wycena skopiowana.")})}
function services(){return '<div class="card"><b>Cennik usług</b>'+db.services.map(function(s,i){return '<div class="item"><input class="input" value="'+esc(s.name)+'" oninput="db.services['+i+'].name=this.value;save()"><input class="input price" type="number" value="'+s.price+'" oninput="db.services['+i+'].price=+this.value;save()"></div>'}).join("")+'<button class="btn secondary" onclick="db.services.push({name:"Nowa usługa",price:0});save();render()">＋ Dodaj usługę</button></div>'}
function clients(){var cs=[...new Set(db.quotes.map(function(q){return q.client}))];return '<div class="card"><b>Klienci</b><p class="muted">Klienci z zapisanych wycen</p>'+cs.map(function(c){return '<div class="card">'+esc(c)+'</div>'}).join("")+'</div>'}
render();