var KEY="wyceny-v1";
var db=JSON.parse(localStorage.getItem(KEY)||'{"quotes":[],"services":[]}');
var pictures={
"Monitoring":"https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=900&q=85",
"Sieć":"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=85",
"MikroTik":"https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=85",
"Ubiquiti":"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=85",
"Anteny":"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85",
"Okablowanie":"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=85",
"Materiały":"https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=900&q=85",
"Rack":"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=85",
"Usługi":"https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=900&q=85"
};
var catalog=[
["Kamera IP Dahua","Monitoring"],["Kamera IP Hikvision","Monitoring"],["Kamera HDCVI Dahua","Monitoring"],["Kamera Turbo HD Hikvision","Monitoring"],["Kamera PTZ","Monitoring"],["Kamera Wi-Fi","Monitoring"],["Kamera 4G/LTE","Monitoring"],["Rejestrator NVR","Monitoring"],["Rejestrator XVR","Monitoring"],["Dysk do monitoringu","Monitoring"],
["Switch PoE 4 porty","Sieć"],["Switch PoE 8 portów","Sieć"],["Switch PoE 16 portów","Sieć"],["Switch PoE 24 porty","Sieć"],["Switch Gigabit","Sieć"],["Switch SFP","Sieć"],
["MikroTik hEX","MikroTik"],["MikroTik hEX S","MikroTik"],["MikroTik RB","MikroTik"],["MikroTik CRS","MikroTik"],["MikroTik SXT","MikroTik"],["MikroTik LHG","MikroTik"],["MikroTik wAP","MikroTik"],["MikroTik cAP","MikroTik"],
["Ubiquiti UniFi AP","Ubiquiti"],["Ubiquiti UniFi Switch","Ubiquiti"],["Ubiquiti NanoStation","Ubiquiti"],["Ubiquiti LiteBeam","Ubiquiti"],
["Antena Wi-Fi kierunkowa","Anteny"],["Antena LTE/5G","Anteny"],["Antena DVB-T","Anteny"],["Maszt antenowy","Anteny"],["Uchwyt antenowy","Anteny"],
["UTP Cat.5e","Okablowanie"],["UTP Cat.6","Okablowanie"],["FTP Cat.6","Okablowanie"],["Przewód koncentryczny","Okablowanie"],["Patchcord","Okablowanie"],
["Wtyk RJ45","Materiały"],["Keystone RJ45","Materiały"],["Gniazdo RJ45","Materiały"],["Zasilacz 12V","Materiały"],["Injector PoE","Materiały"],["Zasilacz PoE","Materiały"],
["Szafa rack","Rack"],["Patch panel","Rack"],["Półka rack","Rack"],["Organizer kabli","Rack"],
["Montaż kamery","Usługi"],["Montaż switcha","Usługi"],["Montaż anteny","Usługi"],["Montaż routera","Usługi"],["Konfiguracja MikroTik","Usługi"],["Konfiguracja UniFi","Usługi"],["Konfiguracja NVR","Usługi"],["Konfiguracja kamer","Usługi"],["Konfiguracja sieci","Usługi"],["Zarobienie RJ45","Usługi"],["Test okablowania","Usługi"],["Dojazd","Usługi"],["Pomiar instalacji","Usługi"],["Materiał instalacyjny","Materiały"]
];
if(!Array.isArray(db.services))db.services=[];
catalog.forEach(function(a){if(!db.services.some(function(s){return s.name===a[0]}))db.services.push({name:a[0],price:0,cat:a[1],img:pictures[a[1]]})});
db.services.forEach(function(s){if(!s.cat)s.cat="Inne";if(!s.img)s.img=pictures[s.cat]||pictures["Materiały"]});
localStorage.setItem(KEY,JSON.stringify(db));
var view="home",draft=null,filter="",catFilter="";
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return Number(n||0).toFixed(2).replace(".",",")+" zł"}
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]})}
function go(v){view=v;render()}
function newQuote(){draft={client:"",date:new Date().toISOString().slice(0,10),items:[],note:""};view="new";render()}
function nav(){return '<nav class="nav"><button onclick="go(\'home\')">🏠 Start</button><button onclick="newQuote()">➕ Wycena</button><button onclick="go(\'quotes\')">📋 Wyceny</button><button onclick="go(\'services\')">💰 Cennik</button></nav>'}
function render(){var body=view==="home"?home():view==="new"?editor():view==="quotes"?quotes():services();document.getElementById("app").innerHTML='<header class="top"><h1>Wyceny Montażu</h1><p>Sprzęt i usługi instalacyjne</p></header><main class="wrap">'+body+'</main>'+nav()}
function home(){var sum=db.quotes.reduce(function(a,q){return a+q.total},0);return '<div class="grid"><div class="card"><div class="muted">Liczba wycen</div><div class="stat">'+db.quotes.length+'</div></div><div class="card"><div class="muted">Wartość</div><div class="stat">'+money(sum)+'</div></div></div><button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button><div class="card"><b>📦 Baza sprzętu</b><p class="muted">'+db.services.length+' pozycji. W wyborze nie pokazujemy cen.</p></div>'}
function picker(){var list=db.services.filter(function(s){var okCat=!catFilter||s.cat===catFilter;var q=filter.toLowerCase();return okCat&&(!q||s.name.toLowerCase().indexOf(q)>=0||s.cat.toLowerCase().indexOf(q)>=0)});return '<input class="input search" placeholder="🔎 Szukaj sprzętu lub usługi..." value="'+esc(filter)+'" oninput="filter=this.value;render()"><div class="chips">'+["Wszystkie","Monitoring","Sieć","MikroTik","Ubiquiti","Anteny","Okablowanie","Materiały","Rack","Usługi"].map(function(c){var active=(c==="Wszystkie"&&!catFilter)||c===catFilter;return '<button class="chip '+(active?'active':'')+'" onclick="catFilter='+(c==="Wszystkie"?'""':JSON.stringify(c))+';render()">'+c+'</button>'}).join("")+'</div><div class="picker">'+list.map(function(s){return '<button class="pick" onclick="addServiceName('+JSON.stringify(s.name)+')"><img class="pickimg" src="'+esc(s.img)+'" alt="" onerror="this.style.opacity=.2"><div class="pickinfo"><span class="tag">'+esc(s.cat)+'</span><b>'+esc(s.name)+'</b></div></button>'}).join("")+'</div>'}
function editor(){var rows=draft.items.map(function(x,i){return '<div class="item"><div class="chosen"><b>'+esc(x.name)+'</b></div><input class="input qty" type="number" min="1" value="'+x.qty+'" oninput="draft.items['+i+'].qty=+this.value;refreshTotal()"><input class="input price" type="number" min="0" value="'+x.price+'" oninput="draft.items['+i+'].price=+this.value;refreshTotal()"><button class="btn danger" onclick="draft.items.splice('+i+',1);render()">×</button></div>'}).join("");var total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);return '<button class="btn secondary" onclick="go(\'home\')">← Wróć</button><div class="form"><b>Klient</b><input class="input" placeholder="Imię i nazwisko / firma" value="'+esc(draft.client)+'" oninput="draft.client=this.value"><b>Data</b><input class="input" type="date" value="'+draft.date+'" oninput="draft.date=this.value"><div class="sectionTitle">Wybierz co montujesz</div>'+picker()+'<div class="sectionTitle">Pozycje wyceny</div>'+rows+'<button class="btn secondary" onclick="addItem()">＋ Dodaj własną pozycję</button><div id="total" class="total">Razem: '+money(total)+'</div><textarea class="input" rows="3" placeholder="Uwagi" oninput="draft.note=this.value">'+esc(draft.note)+'</textarea><button class="btn primary" onclick="saveQuote()">💾 Zapisz wycenę</button></div>'}
function addServiceName(name){var s=db.services.find(function(x){return x.name===name});if(!s)return;draft.items.push({name:s.name,qty:1,price:Number(s.price||0)});render()}
function addItem(){draft.items.push({name:"",qty:1,price:0});render()}
function refreshTotal(){var t=draft.items.reduce(function(a,x){return a+x.qty*x.price},0),e=document.getElementById("total");if(e)e.textContent="Razem: "+money(t)}
function saveQuote(){if(!draft.client.trim()){alert("Wpisz klienta.");return}draft.total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);draft.id=Date.now();db.quotes.unshift({...draft});save();view="quotes";render()}
function quotes(){if(!db.quotes.length)return '<div class="empty">Brak wycen.<br><br><button class="btn primary" onclick="newQuote()">Utwórz pierwszą</button></div>';return '<button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button>'+db.quotes.map(function(q){return '<div class="card"><b>'+esc(q.client)+'</b><div class="muted">'+q.date+' · '+q.items.length+' pozycji</div><div class="total">'+money(q.total)+'</div><button class="btn primary" onclick="pobierzPdfWyceny('+q.id+')">📄 PDF</button> <button class="btn secondary" onclick="shareQuote('+q.id+')">📤 Udostępnij</button> <button class="btn danger" onclick="delQuote('+q.id+')">Usuń</button></div>'}).join("")}
function delQuote(id){db.quotes=db.quotes.filter(function(q){return q.id!==id});save();render()}
function shareQuote(id){var q=db.quotes.find(function(x){return x.id===id}),text="WYCENA\nKlient: "+q.client+"\nData: "+q.date+"\n\n"+q.items.map(function(x){return x.name+" × "+x.qty+" = "+money(x.qty*x.price)}).join("\n")+"\n\nRAZEM: "+money(q.total)+(q.note?"\nUwagi: "+q.note:"");if(navigator.share)navigator.share({title:"Wycena",text:text});else navigator.clipboard.writeText(text).then(function(){alert("Wycena skopiowana.")})}
function services(){return '<div class="card"><b>💰 Cennik</b><p class="muted">Tutaj ustawiasz ceny. Na kafelkach wyboru ceny są ukryte.</p>'+db.services.map(function(s,i){return '<div class="item"><img class="miniimg" src="'+esc(s.img)+'"><div class="chosen"><b>'+esc(s.name)+'</b><div class="muted">'+esc(s.cat)+'</div></div><input class="input price" type="number" value="'+s.price+'" oninput="db.services['+i+'].price=+this.value;save()"></div>'}).join("")+'</div>'}
render();