var KEY="wyceny-v1";
var db=JSON.parse(localStorage.getItem(KEY)||'{"quotes":[],"services":[]}');
if(!db.services.length)db.services=[
{name:"Kamera IP",price:150,cat:"Monitoring",img:"https://commons.wikimedia.org/wiki/Special:FilePath/Wifi_Security_camera_-_Tapo_C100.jpg"},
{name:"Switch PoE",price:120,cat:"Sieć",img:"https://commons.wikimedia.org/wiki/Special:FilePath/Ethernet_Switch.jpg"},
{name:"Antena Wi-Fi",price:180,cat:"Sieć",img:"https://commons.wikimedia.org/wiki/Special:FilePath/RP-SMA_WLAN-Antenne_mit_Stecker.jpg"},
{name:"Antena DVB-T",price:150,cat:"Anteny",img:"https://commons.wikimedia.org/wiki/Special:FilePath/Dvbtantennap.jpg"},
{name:"Rejestrator NVR",price:200,cat:"Monitoring",img:"https://commons.wikimedia.org/wiki/Special:FilePath/Network_switches.jpg"},
{name:"Alarm",price:300,cat:"Alarm",img:"https://commons.wikimedia.org/wiki/Special:FilePath/CCTV_with_reflector.jpg"},
{name:"Zamek / wkładka",price:100,cat:"Zabezpieczenia",img:"https://commons.wikimedia.org/wiki/Special:FilePath/CCTV_with_reflector.jpg"},
{name:"Przewód / UTP",price:5,cat:"Materiał",img:"https://commons.wikimedia.org/wiki/Special:FilePath/EthernetSwitch2.jpg"},
{name:"Materiał instalacyjny",price:50,cat:"Materiał",img:"https://commons.wikimedia.org/wiki/Special:FilePath/Panduit%27s_Cable_Tie_Installation_Tool.jpg"},
{name:"Dojazd",price:50,cat:"Usługa",img:"https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80"},
{name:"Montaż / konfiguracja",price:100,cat:"Usługa",img:"https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=800&q=80"}];
var view="home",draft=null;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return Number(n||0).toFixed(2).replace(".",",")+" zł"}
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]})}
function nav(){return '<nav class="nav"><button onclick="go(\'home\')">🏠 Start</button><button onclick="newQuote()">➕ Wycena</button><button onclick="go(\'quotes\')">📋 Wyceny</button><button onclick="go(\'services\')">💰 Cennik</button></nav>'}
function go(v){view=v;render()}
function newQuote(){draft={client:"",date:new Date().toISOString().slice(0,10),items:[],note:""};view="new";render()}
function render(){var body=view==="home"?home():view==="new"?editor():view==="quotes"?quotes():services();document.getElementById("app").innerHTML='<header class="top"><h1>Wyceny Montażu</h1><p>Szybkie wyceny na telefonie</p></header><main class="wrap">'+body+'</main>'+nav()}
function home(){var sum=db.quotes.reduce(function(a,q){return a+q.total},0);return '<div class="grid"><div class="card"><div class="muted">Liczba wycen</div><div class="stat">'+db.quotes.length+'</div></div><div class="card"><div class="muted">Wartość</div><div class="stat">'+money(sum)+'</div></div></div><button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button><div class="card" style="margin-top:12px"><b>Wybierasz urządzenie ze zdjęcia</b><p class="muted">Lista nie pokazuje cen. Cena jest ustawiana dopiero w pozycji wyceny.</p></div>'}
function picker(){return '<div class="pick-title">Wybierz usługę / urządzenie</div><div class="picker">'+db.services.map(function(s,i){return '<button class="pick" onclick="addService('+i+')"><img class="pickimg" src="'+esc(s.img||"")+'" alt="" onerror="this.style.display=\'none\'"><div class="pickinfo"><span class="tag">'+esc(s.cat||"Usługa")+'</span><b>'+esc(s.name)+'</b></div></button>'}).join("")+'</div>'}
function editor(){var rows=draft.items.map(function(x,i){return '<div class="item"><div class="chosen"><b>'+esc(x.name)+'</b></div><input class="input qty" type="number" min="1" value="'+x.qty+'" title="Ilość" oninput="draft.items['+i+'].qty=+this.value;refreshTotal()"><input class="input price" type="number" min="0" value="'+x.price+'" title="Cena" oninput="draft.items['+i+'].price=+this.value;refreshTotal()"><button class="btn danger" onclick="draft.items.splice('+i+',1);render()">×</button></div>'}).join("");var total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);return '<button class="btn secondary" onclick="go(\'home\')">← Wróć</button><div class="form"><b>Klient</b><input class="input" placeholder="Imię i nazwisko / firma" value="'+esc(draft.client)+'" oninput="draft.client=this.value"><b>Data</b><input class="input" type="date" value="'+draft.date+'" oninput="draft.date=this.value">'+picker()+'<b>Pozycje wyceny</b>'+rows+'<button class="btn secondary" onclick="addItem()">＋ Dodaj własną pozycję</button><div id="total" class="total">Razem: '+money(total)+'</div><textarea class="input" rows="3" placeholder="Uwagi" oninput="draft.note=this.value">'+esc(draft.note)+'</textarea><button class="btn primary" onclick="saveQuote()">💾 Zapisz wycenę</button></div>'}
function addService(i){var s=db.services[i];draft.items.push({name:s.name,qty:1,price:s.price});render()}
function addItem(){draft.items.push({name:"",qty:1,price:0});render()}
function refreshTotal(){var t=draft.items.reduce(function(a,x){return a+x.qty*x.price},0),e=document.getElementById("total");if(e)e.textContent="Razem: "+money(t)}
function saveQuote(){if(!draft.client.trim()){alert("Wpisz klienta.");return}draft.total=draft.items.reduce(function(a,x){return a+x.qty*x.price},0);draft.id=Date.now();db.quotes.unshift(draft);save();view="quotes";render()}
function quotes(){if(!db.quotes.length)return '<div class="empty">Brak wycen.<br><br><button class="btn primary" onclick="newQuote()">Utwórz pierwszą</button></div>';return '<button class="btn primary" onclick="newQuote()">➕ Nowa wycena</button>'+db.quotes.map(function(q){return '<div class="card"><b>'+esc(q.client)+'</b><div class="muted">'+q.date+' · '+q.items.length+' pozycji</div><div class="total">'+money(q.total)+'</div><button class="btn primary" onclick="pobierzPdfWyceny('+q.id+')">📄 PDF</button> <button class="btn secondary" onclick="shareQuote('+q.id+')">📤 Udostępnij</button> <button class="btn danger" onclick="delQuote('+q.id+')">Usuń</button></div>'}).join("")}
function delQuote(id){db.quotes=db.quotes.filter(function(q){return q.id!==id});save();render()}
function shareQuote(id){var q=db.quotes.find(function(x){return x.id===id}),text="WYCENA\nKlient: "+q.client+"\nData: "+q.date+"\n\n"+q.items.map(function(x){return x.name+" × "+x.qty+" = "+money(x.qty*x.price)}).join("\n")+"\n\nRAZEM: "+money(q.total)+(q.note?"\nUwagi: "+q.note:"");if(navigator.share)navigator.share({title:"Wycena",text:text});else navigator.clipboard.writeText(text).then(function(){alert("Wycena skopiowana.")})}
function services(){return '<div class="card"><b>💰 Cennik</b><p class="muted">Tutaj ustawiasz ceny. Na liście wyboru ceny są niewidoczne.</p>'+db.services.map(function(s,i){return '<div class="item"><img class="miniimg" src="'+esc(s.img||"")+'" onerror="this.style.display=\'none\'"><input class="input" value="'+esc(s.name)+'" oninput="db.services['+i+'].name=this.value;save()"><input class="input price" type="number" value="'+s.price+'" oninput="db.services['+i+'].price=+this.value;save()"></div>'}).join("")+'</div>'}
render();